### ISSUE TITLE
Track bytes in flight

### ISSUE THREAD

**Issue by Viyom** [Viyom/ns-3-dev-git#2]
**Requirement:** This will be required by PRR algorithm.

**Proposed approach:** BytesInFlight() can be used to track the bytes in flight.

**Hurdle:**  TcpPktsAckedTestSuite fails whenever BytesInFlight() function is called in ProcessAck ().

**Comment by mohittahiliani** [comment]
@Viyom - What is the status of this issue? I believe it is resolved in latest ns-3-dev changes?

**Comment by Viyom** [comment]
Yes Sir. It is resolved.
